// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  rb3Sidebar: [
    {
      type: 'category',
      label: 'RB3 Charting',
      items: [
        'RB3-Charting/intro',

        {
          type: 'category',
          label: 'Moonscraper Guide',
          items: [
            'RB3-Charting/Moonscraper-Guide/intro',
			'RB3-Charting/Moonscraper-Guide/tempomap',
          ],
        },

        {
          type: 'category',
          label: 'Reaper Guide',
          items: [
            'RB3-Charting/Reaper-Guide/intro',
          ],
        },
      ],
    },
  ],

recipesSidebar: [
  {
    type: 'category',
    label: 'Recipes',
    items: [
      {
        type: 'autogenerated',
        dirName: 'Recipes',   // ← this folder name must match exactly
      },
    ],
  },
],
};

export default sidebars;